import type { TutorialStep } from "./types";

export const TUTORIAL_STEPS: TutorialStep[] = [
  {
    id: "objective",
    target: "header-turn",
    title: "Mục tiêu của trò chơi",
    body: "Bạn có 24 quý để điều hành xưởng dệt Müller & Söhne. Mỗi quý, bạn cân bằng ba sức ép: duy trì sản xuất, bảo vệ dòng tiền và kiểm soát xung đột xã hội. Bạn không cần tối đa hóa mọi chỉ số — mỗi lựa chọn đều có cái giá của nó.",
    advance: { kind: "manual" },
    placement: "bottom",
  },
  {
    id: "cash-debt",
    target: "header-cash",
    title: "Tiền mặt và khoản nợ thừa kế",
    body: "Xưởng bắt đầu với $60.000 tiền mặt và $15.000 nợ thừa kế. Nợ không tự biến mất: mỗi quý xưởng phải trả lãi. Tiền mặt giúp xưởng sống sót, nhưng tiền vay không phải là lợi nhuận.",
    advance: { kind: "manual" },
    placement: "bottom",
  },
  {
    id: "indicators",
    target: "dashboard-grid",
    title: "Đọc các chỉ số quý",
    body: "Chi phí tư liệu là vật liệu và phần giá trị máy móc chuyển vào sản phẩm. Quỹ lương là tiền trả cho lao động. Giá trị dôi ra là phần lao động tạo thêm vượt quá lương — không đồng nghĩa với tiền mặt hay lợi nhuận đã bán được. Hiệu suất vốn cho biết lợi nhuận thực so với vốn ứng. Áp lực xã hội tăng khi giờ làm dài, lương thấp, sức khỏe giảm hoặc thất nghiệp tăng.",
    advance: { kind: "manual" },
    placement: "bottom",
  },
  {
    id: "decisions",
    target: "decision-tabs",
    title: "Ba quyết định mỗi quý",
    body: "Mỗi quý bạn chỉ được dùng tối đa 3 nhóm quyết định, và mỗi nhóm chỉ một lần. Sáu nhóm: Ngày lao động (giờ làm), Tiền lương, Nhân sự (tuyển/sa thải), Máy móc (mua/bán), Tích lũy (giữ lại lợi nhuận), Tín dụng (vay/trả nợ). Chọn điều quan trọng nhất thay vì cố điều chỉnh mọi thứ.",
    advance: { kind: "manual" },
    openGroup: "WORKDAY",
    placement: "left",
  },
  {
    id: "preview",
    target: "decision-panel",
    title: "Xem preview trước khi quyết định",
    body: 'Mỗi lựa chọn hợp lệ hiển thị phần "Nếu áp dụng quyết định này" ngay bên dưới. Màu xanh là chỉ số được cải thiện, màu đỏ là cái giá phải trả, dấu ≈ nghĩa là tác động gần như không đổi. Lưu ý: khi bạn click vào một lựa chọn, quyết định sẽ áp dụng ngay lập tức.',
    advance: { kind: "manual" },
    openGroup: "WAGES",
    placement: "left",
  },
  {
    id: "apply",
    target: "decision-panel",
    title: "Ra quyết định đầu tiên",
    body: 'Hãy chọn một quyết định an toàn — ví dụ "Tăng lương 10%" để cải thiện sức khỏe và tinh thần công nhân. Tutorial sẽ tiếp tục sau khi bạn áp dụng bất kỳ quyết định hợp lệ nào.',
    advance: { kind: "decision-applied" },
    openGroup: "WAGES",
    placement: "left",
  },
  {
    id: "end-quarter",
    target: "end-quarter",
    title: "Kết thúc quý",
    body: 'Quyết định chỉ thay đổi điều kiện vận hành. Kết quả thật chỉ xuất hiện khi quý kết thúc — xưởng sẽ sản xuất, bán hàng, trả lương, trả lãi và cập nhật tình hình xã hội. Bạn có thể dùng thêm quyết định hoặc bấm "Kết thúc quý" ngay bây giờ.',
    advance: { kind: "quarter-ended" },
    placement: "left",
  },
  {
    id: "summary",
    target: "log-panel",
    title: "Đọc kết quả quý",
    body: "Giá trị được tạo ra trong sản xuất, nhưng lợi nhuận chỉ được thực hiện khi hàng hóa bán được. Vì vậy xưởng có thể tạo ra phần dôi ra nhưng vẫn lỗ hoặc thiếu tiền mặt nếu hàng không bán được, tồn kho cao hoặc chi phí tín dụng lớn. Bạn đã biết cách vận hành một quý — từ đây, thị trường, công nhân và các đối thủ sẽ phản ứng với lựa chọn của bạn.",
    advance: { kind: "manual" },
    placement: "top",
  },
];
